url: https://ShortestPathLab.github.io
baseurl: /benchmarks
title: Pathfinding Benchmarks
description: Here, you will find various single and multi-agent pathfinding benchmarks # leave blank if you don't want to display a description
description_one: from a wide variety domains and problems in the literature.
description_two: For clarity, each benchmark includes clear attribution and version control.

last_updated: 23 August 2023 # leave blank if you don't want to display last updated

author:
  name: Shortest Path Lab
  affiliation: Monash University
  city-state-zip: 'Wellington Rd, Clayton VIC 3800'
  web: https://github.com/ShortestPathLab

author-short: SPL

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings

# deployment
host: localhost
port: 4000

remote_theme: jez/tufte-pandoc-jekyll

markdown: Pandoc
pandoc:
  extensions:
    - section-divs
    - from: 'markdown+tex_math_single_backslash'
    # - filter: 'pandoc-sidenote'

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /:categories/:year/:month/:day/:title/
timezone: Australia/Melbourne
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
include: ['_pages']
exclude: ['Gemfile']
keep_files: [.admin]
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: code
git:
  branch: main
transfer:
  command: rsync
  settings: -av
  source: _site/
  # destination: ~/Git/EricMFink.github.com/

jquery_version: "1.12.4"
anchorjs_version: "3.2.2"

plugins:
  - jekyll-spaceship
  - jekyll-pandoc
  - github-pages

# Where things are
jekyll-spaceship:
  # default enabled processors
  processors:
    - table-processor
    - mermaid-processor
    - polyfill-processor
    - media-processor
    - emoji-processor
    - element-processor
  mermaid-processor:
    mode: default  # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: mermaid
    syntax:
      code: 'mermaid!'
      custom: ['@startmermaid', '@endmermaid']
    config:
      theme: default
    src: https://mermaid.ink/svg/
  media-processor:
    default:
      id: 'media-{id}'
      class: 'media'
      width: '100%'
      height: 350
      frameborder: 0
      style: 'max-width: 600px; outline: none;'
      allow: 'encrypted-media; picture-in-picture'
  emoji-processor:
    css:
      class: emoji
    src: https://github.githubassets.com/images/icons/emoji/
